[cite_start]image: eclipse-temurin:21-jdk-alpine [cite: 1] # Actualizado a Java 21 para evitar el error de compilación

stages:
  - test

ejecutar_tests:
  stage: test
  script:
    - [cite_start]./mvnw clean test [cite: 2]
  artifacts:
    [cite_start]name: "reporte-jacoco-${CI_COMMIT_REF_SLUG}" [cite: 2]
    [cite_start]when: always [cite: 2]
    [cite_start]paths: [cite: 2]
      - [cite_start]target/site/jacoco/ [cite: 2]     
      - [cite_start]build/reports/jacoco/ [cite: 2]   
    [cite_start]expire_in: 1 week [cite: 2] # Corregido: Ahora está correctamente alineado dentro de artifacts