[cite_start]image: eclipse-temurin:21-jdk-alpine [cite: 1]

stages:
  - test

ejecutar_tests:
  stage: test
  script:
    - ./mvnw clean install
  artifacts:
    name: "reporte-jacoco-${CI_COMMIT_REF_SLUG}"
    when: always
    paths:
      - target/site/jacoco/      
      - build/reports/jacoco/    
    [cite_start]expire_in: 1 week [cite: 2] # <-- Corregido: Ahora está bien alineado